import type { AdjectiveCatalogEntry } from "./types";

export const n5AdjectiveCatalog = [
  {
    id: "ookii",
    kind: "i",
    japanese: "大きい",
    reading: "おおきい",
    romaji: "ookii",
    meaningEs: "grande",
    meaningEn: "big",
    tags: ["n5", "size"],
  },
  {
    id: "chiisai",
    kind: "i",
    japanese: "小さい",
    reading: "ちいさい",
    romaji: "chiisai",
    meaningEs: "pequeño",
    meaningEn: "small",
    tags: ["n5", "size"],
  },
  {
    id: "atarashii",
    kind: "i",
    japanese: "新しい",
    reading: "あたらしい",
    romaji: "atarashii",
    meaningEs: "nuevo",
    meaningEn: "new",
    tags: ["n5"],
  },
  {
    id: "furui",
    kind: "i",
    japanese: "古い",
    reading: "ふるい",
    romaji: "furui",
    meaningEs: "viejo",
    meaningEn: "old",
    tags: ["n5"],
  },
  {
    id: "ii_yoi",
    kind: "i",
    japanese: "いい",
    reading: "いい",
    romaji: "ii/yoi",
    meaningEs: "bueno",
    meaningEn: "good",
    tags: ["n5", "irregular"],
    notes: "Usa el tallo よ para formas negativas y pasadas.",
    irregularStem: "よ",
  },
  {
    id: "warui",
    kind: "i",
    japanese: "悪い",
    reading: "わるい",
    romaji: "warui",
    meaningEs: "malo",
    meaningEn: "bad",
    tags: ["n5"],
  },
  {
    id: "atsui",
    kind: "i",
    japanese: "暑い",
    reading: "あつい",
    romaji: "atsui",
    meaningEs: "caluroso",
    meaningEn: "hot",
    tags: ["n5", "weather"],
  },
  {
    id: "samui",
    kind: "i",
    japanese: "寒い",
    reading: "さむい",
    romaji: "samui",
    meaningEs: "frio",
    meaningEn: "cold",
    tags: ["n5", "weather"],
  },
  {
    id: "takai",
    kind: "i",
    japanese: "高い",
    reading: "たかい",
    romaji: "takai",
    meaningEs: "alto/caro",
    meaningEn: "tall/expensive",
    tags: ["n5"],
  },
  {
    id: "yasui",
    kind: "i",
    japanese: "安い",
    reading: "やすい",
    romaji: "yasui",
    meaningEs: "barato",
    meaningEn: "cheap",
    tags: ["n5"],
  },
  {
    id: "omoshiroi",
    kind: "i",
    japanese: "面白い",
    reading: "おもしろい",
    romaji: "omoshiroi",
    meaningEs: "interesante/divertido",
    meaningEn: "interesting/funny",
    tags: ["n5"],
  },
  {
    id: "muzukashii",
    kind: "i",
    japanese: "難しい",
    reading: "むずかしい",
    romaji: "muzukashii",
    meaningEs: "dificil",
    meaningEn: "difficult",
    tags: ["n5"],
  },
  {
    id: "kantan",
    kind: "na",
    japanese: "簡単",
    reading: "かんたん",
    romaji: "kantan",
    meaningEs: "facil/simple",
    meaningEn: "easy/simple",
    tags: ["n5"],
  },
  {
    id: "shizuka",
    kind: "na",
    japanese: "静か",
    reading: "しずか",
    romaji: "shizuka",
    meaningEs: "tranquilo/silencioso",
    meaningEn: "quiet",
    tags: ["n5"],
  },
  {
    id: "nigiyaka",
    kind: "na",
    japanese: "賑やか",
    reading: "にぎやか",
    romaji: "nigiyaka",
    meaningEs: "animado/concurrido",
    meaningEn: "lively/busy",
    tags: ["n5"],
  },
  {
    id: "kirei",
    kind: "na",
    japanese: "きれい",
    reading: "きれい",
    romaji: "kirei",
    meaningEs: "bonito/limpio",
    meaningEn: "pretty/clean",
    tags: ["n5"],
    notes: "Termina en い, pero se comporta como adjetivo na.",
  },
  {
    id: "genki",
    kind: "na",
    japanese: "元気",
    reading: "げんき",
    romaji: "genki",
    meaningEs: "saludable/con energia",
    meaningEn: "healthy/energetic",
    tags: ["n5"],
  },
  {
    id: "benri",
    kind: "na",
    japanese: "便利",
    reading: "べんり",
    romaji: "benri",
    meaningEs: "conveniente/util",
    meaningEn: "convenient/useful",
    tags: ["n5"],
  },
  {
    id: "oishii",
    kind: "i",
    japanese: "おいしい",
    reading: "おいしい",
    romaji: "oishii",
    meaningEs: "delicioso",
    meaningEn: "delicious",
    tags: ["n5", "food"],
  },
  {
    id: "amai",
    kind: "i",
    japanese: "甘い",
    reading: "あまい",
    romaji: "amai",
    meaningEs: "dulce",
    meaningEn: "sweet",
    tags: ["n5", "food"],
  },
  {
    id: "karai",
    kind: "i",
    japanese: "辛い",
    reading: "からい",
    romaji: "karai",
    meaningEs: "picante",
    meaningEn: "spicy",
    tags: ["n5", "food"],
  },
  {
    id: "hayai",
    kind: "i",
    japanese: "早い",
    reading: "はやい",
    romaji: "hayai",
    meaningEs: "temprano; rapido",
    meaningEn: "early; fast",
    tags: ["n5"],
  },
  {
    id: "osoi",
    kind: "i",
    japanese: "遅い",
    reading: "おそい",
    romaji: "osoi",
    meaningEs: "tarde; lento",
    meaningEn: "late; slow",
    tags: ["n5"],
  },
  {
    id: "chikai",
    kind: "i",
    japanese: "近い",
    reading: "ちかい",
    romaji: "chikai",
    meaningEs: "cercano",
    meaningEn: "near",
    tags: ["n5"],
  },
  {
    id: "tooi",
    kind: "i",
    japanese: "遠い",
    reading: "とおい",
    romaji: "tooi",
    meaningEs: "lejano",
    meaningEn: "far",
    tags: ["n5"],
  },
  {
    id: "omoi",
    kind: "i",
    japanese: "重い",
    reading: "おもい",
    romaji: "omoi",
    meaningEs: "pesado",
    meaningEn: "heavy",
    tags: ["n5"],
  },
  {
    id: "karui",
    kind: "i",
    japanese: "軽い",
    reading: "かるい",
    romaji: "karui",
    meaningEs: "ligero",
    meaningEn: "light",
    tags: ["n5"],
  },
  {
    id: "hiroi",
    kind: "i",
    japanese: "広い",
    reading: "ひろい",
    romaji: "hiroi",
    meaningEs: "amplio",
    meaningEn: "wide",
    tags: ["n5"],
  },
  {
    id: "semai",
    kind: "i",
    japanese: "狭い",
    reading: "せまい",
    romaji: "semai",
    meaningEs: "estrecho",
    meaningEn: "narrow",
    tags: ["n5"],
  },
  {
    id: "akarui",
    kind: "i",
    japanese: "明るい",
    reading: "あかるい",
    romaji: "akarui",
    meaningEs: "brillante; alegre",
    meaningEn: "bright; cheerful",
    tags: ["n5"],
  },
  {
    id: "kurai",
    kind: "i",
    japanese: "暗い",
    reading: "くらい",
    romaji: "kurai",
    meaningEs: "oscuro",
    meaningEn: "dark",
    tags: ["n5"],
  },
  {
    id: "tanoshii",
    kind: "i",
    japanese: "楽しい",
    reading: "たのしい",
    romaji: "tanoshii",
    meaningEs: "divertido",
    meaningEn: "fun",
    tags: ["n5"],
  },
  {
    id: "isogashii",
    kind: "i",
    japanese: "忙しい",
    reading: "いそがしい",
    romaji: "isogashii",
    meaningEs: "ocupado",
    meaningEn: "busy",
    tags: ["n5"],
  },
  {
    id: "himana",
    kind: "na",
    japanese: "暇",
    reading: "ひま",
    romaji: "hima",
    meaningEs: "libre; desocupado",
    meaningEn: "free; not busy",
    tags: ["n5"],
  },
  {
    id: "suki",
    kind: "na",
    japanese: "好き",
    reading: "すき",
    romaji: "suki",
    meaningEs: "gustar; favorito",
    meaningEn: "liked; favorite",
    tags: ["n5"],
  },
  {
    id: "kirai",
    kind: "na",
    japanese: "嫌い",
    reading: "きらい",
    romaji: "kirai",
    meaningEs: "desagradable; odiado",
    meaningEn: "disliked",
    tags: ["n5"],
    notes: "Termina en い, pero se comporta como adjetivo na.",
  },
  {
    id: "jouzu",
    kind: "na",
    japanese: "上手",
    reading: "じょうず",
    romaji: "jouzu",
    meaningEs: "habil; bueno en algo",
    meaningEn: "skillful",
    tags: ["n5"],
  },
  {
    id: "heta",
    kind: "na",
    japanese: "下手",
    reading: "へた",
    romaji: "heta",
    meaningEs: "torpe; malo en algo",
    meaningEn: "unskillful",
    tags: ["n5"],
  },
  {
    id: "taisetsu",
    kind: "na",
    japanese: "大切",
    reading: "たいせつ",
    romaji: "taisetsu",
    meaningEs: "importante; valioso",
    meaningEn: "important",
    tags: ["n5"],
  },
  {
    id: "atsui_hot",
    kind: "i",
    japanese: "熱い",
    reading: "あつい",
    romaji: "atsui",
    meaningEs: "caliente (al tacto)",
    meaningEn: "hot (to touch)",
    tags: ["n5"],
  },
  {
    id: "tsumetai",
    kind: "i",
    japanese: "冷たい",
    reading: "つめたい",
    romaji: "tsumetai",
    meaningEs: "frío (al tacto)",
    meaningEn: "cold (to touch)",
    tags: ["n5"],
  },
  {
    id: "atatakai",
    kind: "i",
    japanese: "暖かい",
    reading: "あたたかい",
    romaji: "atatakai",
    meaningEs: "cálido; templado",
    meaningEn: "warm",
    tags: ["n5", "weather"],
  },
  {
    id: "suzushii",
    kind: "i",
    japanese: "涼しい",
    reading: "すずしい",
    romaji: "suzushii",
    meaningEs: "fresco",
    meaningEn: "cool",
    tags: ["n5", "weather"],
  },
  {
    id: "tsuyoi",
    kind: "i",
    japanese: "強い",
    reading: "つよい",
    romaji: "tsuyoi",
    meaningEs: "fuerte",
    meaningEn: "strong",
    tags: ["n5"],
  },
  {
    id: "yowai",
    kind: "i",
    japanese: "弱い",
    reading: "よわい",
    romaji: "yowai",
    meaningEs: "débil",
    meaningEn: "weak",
    tags: ["n5"],
  },
  {
    id: "nagai",
    kind: "i",
    japanese: "長い",
    reading: "ながい",
    romaji: "nagai",
    meaningEs: "largo",
    meaningEn: "long",
    tags: ["n5"],
  },
  {
    id: "mijikai",
    kind: "i",
    japanese: "短い",
    reading: "みじかい",
    romaji: "mijikai",
    meaningEs: "corto",
    meaningEn: "short",
    tags: ["n5"],
  },
  {
    id: "ooi",
    kind: "i",
    japanese: "多い",
    reading: "おおい",
    romaji: "ooi",
    meaningEs: "mucho; numeroso",
    meaningEn: "many",
    tags: ["n5"],
  },
  {
    id: "sukunai",
    kind: "i",
    japanese: "少ない",
    reading: "すくない",
    romaji: "sukunai",
    meaningEs: "poco; escaso",
    meaningEn: "few",
    tags: ["n5"],
  },
  {
    id: "hayai_fast",
    kind: "i",
    japanese: "速い",
    reading: "はやい",
    romaji: "hayai",
    meaningEs: "rápido (velocidad)",
    meaningEn: "fast",
    tags: ["n5"],
  },
  {
    id: "itai",
    kind: "i",
    japanese: "痛い",
    reading: "いたい",
    romaji: "itai",
    meaningEs: "doloroso",
    meaningEn: "painful",
    tags: ["n5"],
  },
  {
    id: "abunai",
    kind: "i",
    japanese: "危ない",
    reading: "あぶない",
    romaji: "abunai",
    meaningEs: "peligroso",
    meaningEn: "dangerous",
    tags: ["n5"],
  },
  {
    id: "kitanai",
    kind: "i",
    japanese: "汚い",
    reading: "きたない",
    romaji: "kitanai",
    meaningEs: "sucio",
    meaningEn: "dirty",
    tags: ["n5"],
  },
  {
    id: "kawaii",
    kind: "i",
    japanese: "可愛い",
    reading: "かわいい",
    romaji: "kawaii",
    meaningEs: "lindo; tierno",
    meaningEn: "cute",
    tags: ["n5"],
  },
  {
    id: "urusai",
    kind: "i",
    japanese: "うるさい",
    reading: "うるさい",
    romaji: "urusai",
    meaningEs: "ruidoso; molesto",
    meaningEn: "noisy",
    tags: ["n5"],
  },
  {
    id: "wakai",
    kind: "i",
    japanese: "若い",
    reading: "わかい",
    romaji: "wakai",
    meaningEs: "joven",
    meaningEn: "young",
    tags: ["n5"],
  },
  {
    id: "shiroi",
    kind: "i",
    japanese: "白い",
    reading: "しろい",
    romaji: "shiroi",
    meaningEs: "blanco",
    meaningEn: "white",
    tags: ["n5", "color"],
  },
  {
    id: "kuroi",
    kind: "i",
    japanese: "黒い",
    reading: "くろい",
    romaji: "kuroi",
    meaningEs: "negro",
    meaningEn: "black",
    tags: ["n5", "color"],
  },
  {
    id: "akai",
    kind: "i",
    japanese: "赤い",
    reading: "あかい",
    romaji: "akai",
    meaningEs: "rojo",
    meaningEn: "red",
    tags: ["n5", "color"],
  },
  {
    id: "aoi",
    kind: "i",
    japanese: "青い",
    reading: "あおい",
    romaji: "aoi",
    meaningEs: "azul",
    meaningEn: "blue",
    tags: ["n5", "color"],
  },
  {
    id: "marui",
    kind: "i",
    japanese: "丸い",
    reading: "まるい",
    romaji: "marui",
    meaningEs: "redondo",
    meaningEn: "round",
    tags: ["n5"],
  },
  {
    id: "futoi",
    kind: "i",
    japanese: "太い",
    reading: "ふとい",
    romaji: "futoi",
    meaningEs: "grueso; gordo",
    meaningEn: "thick; fat",
    tags: ["n5"],
  },
  {
    id: "hosoi",
    kind: "i",
    japanese: "細い",
    reading: "ほそい",
    romaji: "hosoi",
    meaningEs: "delgado; fino",
    meaningEn: "thin; slender",
    tags: ["n5"],
  },
  {
    id: "mazui",
    kind: "i",
    japanese: "まずい",
    reading: "まずい",
    romaji: "mazui",
    meaningEs: "feo de sabor",
    meaningEn: "bad-tasting",
    tags: ["n5", "food"],
  },
  {
    id: "nigai",
    kind: "i",
    japanese: "苦い",
    reading: "にがい",
    romaji: "nigai",
    meaningEs: "amargo",
    meaningEn: "bitter",
    tags: ["n5", "food"],
  },
  {
    id: "hoshii",
    kind: "i",
    japanese: "欲しい",
    reading: "ほしい",
    romaji: "hoshii",
    meaningEs: "deseado; querer",
    meaningEn: "wanted",
    tags: ["n5"],
  },
  {
    id: "daijoubu",
    kind: "na",
    japanese: "大丈夫",
    reading: "だいじょうぶ",
    romaji: "daijoubu",
    meaningEs: "está bien; seguro",
    meaningEn: "all right; okay",
    tags: ["n5"],
  },
  {
    id: "taihen",
    kind: "na",
    japanese: "大変",
    reading: "たいへん",
    romaji: "taihen",
    meaningEs: "duro; terrible",
    meaningEn: "tough; awful",
    tags: ["n5"],
  },
  {
    id: "yuumei",
    kind: "na",
    japanese: "有名",
    reading: "ゆうめい",
    romaji: "yuumei",
    meaningEs: "famoso",
    meaningEn: "famous",
    tags: ["n5"],
  },
  {
    id: "shinsetsu",
    kind: "na",
    japanese: "親切",
    reading: "しんせつ",
    romaji: "shinsetsu",
    meaningEs: "amable",
    meaningEn: "kind",
    tags: ["n5"],
  },
  {
    id: "iroiro",
    kind: "na",
    japanese: "色々",
    reading: "いろいろ",
    romaji: "iroiro",
    meaningEs: "variado; diverso",
    meaningEn: "various",
    tags: ["n5"],
  },
  {
    id: "daisuki",
    kind: "na",
    japanese: "大好き",
    reading: "だいすき",
    romaji: "daisuki",
    meaningEs: "encantar; favorito",
    meaningEn: "loved; favorite",
    tags: ["n5"],
  },
  {
    id: "teinei",
    kind: "na",
    japanese: "丁寧",
    reading: "ていねい",
    romaji: "teinei",
    meaningEs: "cortés; cuidadoso",
    meaningEn: "polite; careful",
    tags: ["n5"],
  },
  {
    id: "hitsuyou",
    kind: "na",
    japanese: "必要",
    reading: "ひつよう",
    romaji: "hitsuyou",
    meaningEs: "necesario",
    meaningEn: "necessary",
    tags: ["n5"],
  },
  {
    id: "jiyuu",
    kind: "na",
    japanese: "自由",
    reading: "じゆう",
    romaji: "jiyuu",
    meaningEs: "libre",
    meaningEn: "free",
    tags: ["n5"],
  },
] as const satisfies readonly AdjectiveCatalogEntry[];

export type N5AdjectiveId = (typeof n5AdjectiveCatalog)[number]["id"];

export function getAdjectiveById(id: string): AdjectiveCatalogEntry | undefined {
  return n5AdjectiveCatalog.find((adjective) => adjective.id === id);
}
