import type { AdjectiveCatalogEntry } from "./types";

export const n5AdjectiveCatalog = [
  {
    id: "ookii",
    kind: "i",
    japanese: "大きい",
    reading: "おおきい",
    romaji: "ookii",
    meaningEs: "grande",
    meaningEn: "big",
    tags: ["n5", "size"],
  },
  {
    id: "chiisai",
    kind: "i",
    japanese: "小さい",
    reading: "ちいさい",
    romaji: "chiisai",
    meaningEs: "pequeño",
    meaningEn: "small",
    tags: ["n5", "size"],
  },
  {
    id: "atarashii",
    kind: "i",
    japanese: "新しい",
    reading: "あたらしい",
    romaji: "atarashii",
    meaningEs: "nuevo",
    meaningEn: "new",
    tags: ["n5"],
  },
  {
    id: "furui",
    kind: "i",
    japanese: "古い",
    reading: "ふるい",
    romaji: "furui",
    meaningEs: "viejo",
    meaningEn: "old",
    tags: ["n5"],
  },
  {
    id: "ii_yoi",
    kind: "i",
    japanese: "いい",
    reading: "いい",
    romaji: "ii/yoi",
    meaningEs: "bueno",
    meaningEn: "good",
    tags: ["n5", "irregular"],
    notes: "Usa el tallo よ para formas negativas y pasadas.",
    irregularStem: "よ",
  },
  {
    id: "warui",
    kind: "i",
    japanese: "悪い",
    reading: "わるい",
    romaji: "warui",
    meaningEs: "malo",
    meaningEn: "bad",
    tags: ["n5"],
  },
  {
    id: "atsui",
    kind: "i",
    japanese: "暑い",
    reading: "あつい",
    romaji: "atsui",
    meaningEs: "caluroso",
    meaningEn: "hot",
    tags: ["n5", "weather"],
  },
  {
    id: "samui",
    kind: "i",
    japanese: "寒い",
    reading: "さむい",
    romaji: "samui",
    meaningEs: "frio",
    meaningEn: "cold",
    tags: ["n5", "weather"],
  },
  {
    id: "takai",
    kind: "i",
    japanese: "高い",
    reading: "たかい",
    romaji: "takai",
    meaningEs: "alto/caro",
    meaningEn: "tall/expensive",
    tags: ["n5"],
  },
  {
    id: "yasui",
    kind: "i",
    japanese: "安い",
    reading: "やすい",
    romaji: "yasui",
    meaningEs: "barato",
    meaningEn: "cheap",
    tags: ["n5"],
  },
  {
    id: "omoshiroi",
    kind: "i",
    japanese: "面白い",
    reading: "おもしろい",
    romaji: "omoshiroi",
    meaningEs: "interesante/divertido",
    meaningEn: "interesting/funny",
    tags: ["n5"],
  },
  {
    id: "muzukashii",
    kind: "i",
    japanese: "難しい",
    reading: "むずかしい",
    romaji: "muzukashii",
    meaningEs: "dificil",
    meaningEn: "difficult",
    tags: ["n5"],
  },
  {
    id: "kantan",
    kind: "na",
    japanese: "簡単",
    reading: "かんたん",
    romaji: "kantan",
    meaningEs: "facil/simple",
    meaningEn: "easy/simple",
    tags: ["n5"],
  },
  {
    id: "shizuka",
    kind: "na",
    japanese: "静か",
    reading: "しずか",
    romaji: "shizuka",
    meaningEs: "tranquilo/silencioso",
    meaningEn: "quiet",
    tags: ["n5"],
  },
  {
    id: "nigiyaka",
    kind: "na",
    japanese: "賑やか",
    reading: "にぎやか",
    romaji: "nigiyaka",
    meaningEs: "animado/concurrido",
    meaningEn: "lively/busy",
    tags: ["n5"],
  },
  {
    id: "kirei",
    kind: "na",
    japanese: "きれい",
    reading: "きれい",
    romaji: "kirei",
    meaningEs: "bonito/limpio",
    meaningEn: "pretty/clean",
    tags: ["n5"],
    notes: "Termina en い, pero se comporta como adjetivo na.",
  },
  {
    id: "genki",
    kind: "na",
    japanese: "元気",
    reading: "げんき",
    romaji: "genki",
    meaningEs: "saludable/con energia",
    meaningEn: "healthy/energetic",
    tags: ["n5"],
  },
  {
    id: "benri",
    kind: "na",
    japanese: "便利",
    reading: "べんり",
    romaji: "benri",
    meaningEs: "conveniente/util",
    meaningEn: "convenient/useful",
    tags: ["n5"],
  },
  {
    id: "oishii",
    kind: "i",
    japanese: "おいしい",
    reading: "おいしい",
    romaji: "oishii",
    meaningEs: "delicioso",
    meaningEn: "delicious",
    tags: ["n5", "food"],
  },
  {
    id: "amai",
    kind: "i",
    japanese: "甘い",
    reading: "あまい",
    romaji: "amai",
    meaningEs: "dulce",
    meaningEn: "sweet",
    tags: ["n5", "food"],
  },
  {
    id: "karai",
    kind: "i",
    japanese: "辛い",
    reading: "からい",
    romaji: "karai",
    meaningEs: "picante",
    meaningEn: "spicy",
    tags: ["n5", "food"],
  },
  {
    id: "hayai",
    kind: "i",
    japanese: "早い",
    reading: "はやい",
    romaji: "hayai",
    meaningEs: "temprano; rapido",
    meaningEn: "early; fast",
    tags: ["n5"],
  },
  {
    id: "osoi",
    kind: "i",
    japanese: "遅い",
    reading: "おそい",
    romaji: "osoi",
    meaningEs: "tarde; lento",
    meaningEn: "late; slow",
    tags: ["n5"],
  },
  {
    id: "chikai",
    kind: "i",
    japanese: "近い",
    reading: "ちかい",
    romaji: "chikai",
    meaningEs: "cercano",
    meaningEn: "near",
    tags: ["n5"],
  },
  {
    id: "tooi",
    kind: "i",
    japanese: "遠い",
    reading: "とおい",
    romaji: "tooi",
    meaningEs: "lejano",
    meaningEn: "far",
    tags: ["n5"],
  },
  {
    id: "omoi",
    kind: "i",
    japanese: "重い",
    reading: "おもい",
    romaji: "omoi",
    meaningEs: "pesado",
    meaningEn: "heavy",
    tags: ["n5"],
  },
  {
    id: "karui",
    kind: "i",
    japanese: "軽い",
    reading: "かるい",
    romaji: "karui",
    meaningEs: "ligero",
    meaningEn: "light",
    tags: ["n5"],
  },
  {
    id: "hiroi",
    kind: "i",
    japanese: "広い",
    reading: "ひろい",
    romaji: "hiroi",
    meaningEs: "amplio",
    meaningEn: "wide",
    tags: ["n5"],
  },
  {
    id: "semai",
    kind: "i",
    japanese: "狭い",
    reading: "せまい",
    romaji: "semai",
    meaningEs: "estrecho",
    meaningEn: "narrow",
    tags: ["n5"],
  },
  {
    id: "akarui",
    kind: "i",
    japanese: "明るい",
    reading: "あかるい",
    romaji: "akarui",
    meaningEs: "brillante; alegre",
    meaningEn: "bright; cheerful",
    tags: ["n5"],
  },
  {
    id: "kurai",
    kind: "i",
    japanese: "暗い",
    reading: "くらい",
    romaji: "kurai",
    meaningEs: "oscuro",
    meaningEn: "dark",
    tags: ["n5"],
  },
  {
    id: "tanoshii",
    kind: "i",
    japanese: "楽しい",
    reading: "たのしい",
    romaji: "tanoshii",
    meaningEs: "divertido",
    meaningEn: "fun",
    tags: ["n5"],
  },
  {
    id: "isogashii",
    kind: "i",
    japanese: "忙しい",
    reading: "いそがしい",
    romaji: "isogashii",
    meaningEs: "ocupado",
    meaningEn: "busy",
    tags: ["n5"],
  },
  {
    id: "himana",
    kind: "na",
    japanese: "暇",
    reading: "ひま",
    romaji: "hima",
    meaningEs: "libre; desocupado",
    meaningEn: "free; not busy",
    tags: ["n5"],
  },
  {
    id: "suki",
    kind: "na",
    japanese: "好き",
    reading: "すき",
    romaji: "suki",
    meaningEs: "gustar; favorito",
    meaningEn: "liked; favorite",
    tags: ["n5"],
  },
  {
    id: "kirai",
    kind: "na",
    japanese: "嫌い",
    reading: "きらい",
    romaji: "kirai",
    meaningEs: "desagradable; odiado",
    meaningEn: "disliked",
    tags: ["n5"],
    notes: "Termina en い, pero se comporta como adjetivo na.",
  },
  {
    id: "jouzu",
    kind: "na",
    japanese: "上手",
    reading: "じょうず",
    romaji: "jouzu",
    meaningEs: "habil; bueno en algo",
    meaningEn: "skillful",
    tags: ["n5"],
  },
  {
    id: "heta",
    kind: "na",
    japanese: "下手",
    reading: "へた",
    romaji: "heta",
    meaningEs: "torpe; malo en algo",
    meaningEn: "unskillful",
    tags: ["n5"],
  },
  {
    id: "taisetsu",
    kind: "na",
    japanese: "大切",
    reading: "たいせつ",
    romaji: "taisetsu",
    meaningEs: "importante; valioso",
    meaningEn: "important",
    tags: ["n5"],
  },
] as const satisfies readonly AdjectiveCatalogEntry[];

export type N5AdjectiveId = (typeof n5AdjectiveCatalog)[number]["id"];

export function getAdjectiveById(id: string): AdjectiveCatalogEntry | undefined {
  return n5AdjectiveCatalog.find((adjective) => adjective.id === id);
}
